version: 0.2

phases:
  pre_build:
    commands:
      - echo "== Login ECR =="
      - aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo "== Testes =="
      - npm ci
      - npm test
      - echo "== Build Docker =="
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag  $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI:latest
  post_build:
    commands:
      - echo "== Push =="
      - docker push $ECR_URI:latest
artifacts: {}
